version: '3'

volumes:
    mysql_data:
    django_cache:

services:
  db:
    build: ./infra/docker/mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3308:3306

  web:
    build: ./infra/docker/python
    tty: true
    volumes:
      - ./src:/code
    restart: always
    ports:
      - 5001:5000
    command: flask run --host=0.0.0.0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=flask
      - PMA_PASSWORD=secret
    ports:
      - 8888:80
    depends_on:
      - db
